stages:
  prepare_dataset:
    cmd: Rscript code/R/scripts/prepare_dataset_cmd.R --input rawdata/seba-caprino-feature-engineering-seba-abdel.tsv
      --output data/preprocessed/seba-caprino-preprocessed.tsv
    deps:
    - code/R/scripts/prepare_dataset_cmd.R
    - code/R/scripts/create_numeric_features.R
    - code/R/scripts/create_lag_features.R
    - rawdata/seba-caprino-feature-engineering-seba-abdel.tsv
    outs:
    - data/preprocessed
    
  select_initial_features:
    cmd: Rscript code/R/scripts/select_initial_features_cmd.R --input data/preprocessed/seba-caprino-preprocessed.tsv
      --output data/initial_features/seba-caprino-preprocessed-initial-features.tsv 
    deps:
    - code/R/scripts/select_initial_features.R
    - code/R/scripts/select_initial_features_cmd.R
    - data/preprocessed/seba-caprino-preprocessed.tsv
    outs:
    - data/initial_features
    
  separate_dataset:
    cmd: Rscript code/R/scripts/separate_dataset_cmd.R --input data/initial_features/seba-caprino-preprocessed-initial-features.tsv 
      --output data/split/seba-caprino
    deps:
    - code/R/scripts/separate_dataset_cmd.R
    - code/R/scripts/separate_dataset.R
    - data/initial_features/seba-caprino-preprocessed-initial-features.tsv 
    outs:
    - data/split
    params:
    - separate_dataset.excluded_anim
    metrics:
    - metrics/separate_dataset.yaml:
        cache: false
    
  select_features_boruta:
    cmd: Rscript code/R/scripts/select_features_boruta_cmd.R --input data/split/seba-caprino_features.tsv 
      --output data/topnfeatures/seba-caprino
    deps:
    - code/R/scripts/select_features_boruta_cmd.R
    - code/R/scripts/select_features_boruta.R
    - data/split/seba-caprino_features.tsv  
    metrics:
    - select_features_boruta.yaml:
        cache: false
    params:
    - select_features_boruta.maxnfeat
    - select_features_boruta.numsamp
    outs:
    - data/topnfeatures
    
  train_model:
    cmd: Rscript code/R/scripts/train_model_cmd.R --input data/split/seba-caprino_features.tsv 
      --selected_variables data/topnfeatures/seba-caprino_selected_features.tsv --model models/boost/seba-caprino
    deps:
    - code/R/scripts/train_model_cmd.R
    - code/R/scripts/train_model.R
    - data/split/seba-caprino_features.tsv
    - data/topnfeatures/seba-caprino_selected_features.tsv
    outs:
    - models/boost
    metrics:
    - metrics/train_model.yaml:
        cache: false
