select_features_boruta:
  maxnfeat: 25
  numsamp: 30

select_initial:
  features:
  - Anim
  - Standing
  - Active
  - Lying
  - Steps
  - '%HeadDown'
  - DFL1
  - DFL2
  - DFL3
  - DFA12
  - DFA123
  - DBL1
  - DBL2
  - DBL3
  - DBA12
  - DBA123
  - X_Actlog
  - Y_Actlog
  - X_Act
  - Y_Act
  - Stepslog
  - Steps
  - distance(m)log
  - distance(m)
  - VarXYlog
  - DiffXYlog
  - MeanXYlog
  - VarXY
  - DiffXY
  - MeanXY
  - prev_Active1
  - prev_Active1
  - prev_Active2
  - prev_Active3
  - prev_Standing1
  - prev_Standing2
  - prev_Standing3
  - prev_Lying1
  - prev_Lying2
  - prev_Lying3
  - prev_steps1
  - prev_steps2
  - prev_steps3
separate_dataset:
  excluded_anim:
  - 1553
  - 1635
  - 1779
  - 505081
  - 505075
  - 505080

calculate_shap:
  nsim: 10
