---
title: "R Notebook"
output: html_notebook
---
```{r}
library(caret)
library(dplyr)
```

# PROBLEMATIC CODE

## Using BORUTA for Feature Selection

### Select TOP N features
```{r}
source("../functions/select_features_boruta.R")
train_dataset_boruta<- readr::read_tsv("../../../data/split/seba-caprino_features.tsv")
  train_dataset_boruta$Activity<-as.factor(train_dataset_boruta$Activity)
var_importance_boruta_final<-select_maxn_features(train_dataset_boruta
                                                  %>% select(-Anim),
                                 max_num_of_feat = 20,
                                 num_of_samp = 30)
var_importance_boruta_final
```

```{r}
ctrl_fast <- trainControl(
  method = "cv",
  number = 10,
  returnResamp = 'final',
  savePredictions = 'final',
  verboseIter = FALSE,
  classProbs = TRUE,
  allowParallel = TRUE,
  summaryFunction=multiClassSummary
)
```

## Grid Search parameters

```{r}
 grid <- expand.grid(
    depth = c(4),
    learning_rate = c(0.05),
    #iterations = c(10,50,100,500,1000),
    iterations = c(1000),
    l2_leaf_reg = c(3.0),
    #regularization parameter
    rsm = c(1),
    # percentage of features to use at each split selection
    border_count = c(64)
  )
```



## Boost LOOCV
```{r}
setwd("/home/harpo/Dropbox/ongoing-work/git-repos/goat-behavior/")
source("code/R/functions/train_model_loocv.R")
```


```{r message=FALSE}
library(doMC)
registerDoMC(cores = 4)
caret_dataset <- readr::read_delim("../../../data/split/seba-caprino_loocv.tsv",delim='\t')
set.seed(19091974)
samples<-create_loocv_samples(caret_dataset)

loocv_results<- vector(mode = "list", length = length( samples$n_anim))

for (i in seq(1, length(samples$n_anim))) {
  train_dataset_loocv <- caret_dataset[samples$loocv_train[[i]], ]
  train_dataset_loocv$Activity <-
    as.factor(train_dataset_loocv$Activity)
  test_dataset_loocv <- caret_dataset[-samples$loocv_train[[i]], ]
  test_dataset_loocv$Activity <-
    factor(test_dataset_loocv$Activity,
           levels = levels(train_dataset_loocv$Activity))
  
  val_dataset <- train_dataset_loocv %>% sample_frac(.1)
  train_dataset <- setdiff(train_dataset_loocv, val_dataset)
  
  selected_variables <- var_importance_boruta_final 
  
  boostFit <- caret::train(
    x = train_dataset %>%
      select(selected_variables$variable) %>%  na.omit() %>% as.data.frame(),
    y = train_dataset %>%  select(Activity) %>% unlist() %>% unname()  %>% as.factor(),
    method = catboost::catboost.caret,
    tuneGrid = grid,
    metric = 'logLoss',
    verbose = 0,
    trControl = ctrl_fast,
    auto_class_weights = "Balanced",
    use_best_model = TRUE,
    od_type = 'Iter',
    test_pool = catboost.load_pool(
      val_dataset %>%
        select(selected_variables$variable) %>%  na.omit() %>% as.data.frame(),
      label = as.numeric(as.factor(val_dataset$Activity)) - 1
    )
  )
  ## Independent Evaluation
  boostFit_eval <- predict(boostFit,
                           test_dataset_loocv  %>%
                             select(selected_variables$variable))
  cm <-
    confusionMatrix(reference = as.factor(test_dataset_loocv$Activity), boostFit_eval)
  loocv_results[[i]] <- list(
        overall = cm$overall,
        byclass = cm$byClass,
        tab = cm$table,
        predictions = boostFit_eval,
        observations = as.factor(test_dataset_loocv$Activity),
        model = boostFit
      )
}
loocv_results %>% loocv_peformance_metrics
```

```{r}
set.seed(19091974)
results <- 
    train_model_loocv2(caret_dataset = caret_dataset,
                        selected_variables=var_importance_boruta_final,
                      gridsearch = grid,
                      vfrac = 0.1)
results %>% loocv_peformance_metrics
```

```{r}
set.seed(19091974)
results <- 
    train_model_loocv(dataset = caret_dataset,
                        selected_variables=var_importance_boruta_final,
                      gridsearch = grid,
                      vfrac = 0.1)
results %>% loocv_peformance_metrics
```



