---
title: "Pipeline analysis"
output: html_notebook
---
```{r}
library(dplyr)
library(yaml)
```
```{r}
dataset <- readr::read_delim("../../../data/preprocessed/seba-caprino-preprocessed.tsv", delim="\t")

dataset %>% group_by(Anim) %>% count()
```

```{r}
traindata <- readr::read_delim("../../../data/split/seba-caprino_features.tsv",delim="\t")
traindata %>% group_by(Activity) %>% count()
```

```{r}
loocvdata <- readr::read_delim("../../../data/split/seba-caprino_loocv.tsv",delim="\t")
loocvdata %>% group_by(Activity) %>% count()
```

## Results
```{r}
library(ztable)
options(ztable.type='viewer')
r<-readr::read_csv("../../../results.csv")
names(r)<-c("exp","TrR","TrW","TrG","TrGM","Trov","TrMicro",
                  "TeR","TeW","TeG","TeGM","Teov","TeMicro")
r<- r %>% filter(!is.na(exp))
ztable(r %>% as.data.frame() %>% select(c(1,2,3,4,5,8,9,10,11))) %>% makeHeatmap() 
```

```{r}
library(ztable)
options(ztable.type='viewer')
r2<-readr::read_csv("../../../results-resample.csv")
r2 <- r2 %>%  as.data.frame() #%>% select(c(1,2,3,4,5,6,7))
names(r2)<-c("expe","BAcc","BAcc_sd","Sens","Sens_sd","Spec","Spec_sd",
            "reR","reR_sd","reG","reG_sd","reW","reW_sd","reGM","reGM_sd")
r2<- r2 %>% replace(is.na(.), 0)
ztable(r2) %>% makeHeatmap() 
```




```{r}
options(ztable.zebra=1)
options(ztable.zebra.color="platinum")
options(ztable.colnames.bold=TRUE)
cgroup=c("","Resting","Walking","Grazing","Grazing M")
n.cgroup=c(1,3,3,3,3)
cbind(r,r2) %>% select(-expe) %>% drop_na() %>% select(-reW_sd,-reR_sd,-reG_sd,-reGM_sd, -BAcc_sd,-Sens_sd, -Spec_sd,-Teov,-TeMicro) %>% select(exp,reR,TrR,TeR,reW,TrW,TeW,reG,TrG,TeG,reGM,TrGM,TeGM) %>%
   # select(exp,reR,reW,reG,reGM) %>%
    
  
  ztable(size=3) %>% addcgroup(cgroup=cgroup,n.cgroup=n.cgroup)   %>% addRowColor(c(6,9),"gray")
```


## selected variables

### initial
```{r}
initial_variables <- readr::read_tsv("../../../data/split/seba-caprino_features.tsv")
  cbind(train_dataset_boruta %>%  names()  %>% as.data.frame() %>% arrange(desc(.)),
  initial_variables %>% select(-Anim) %>% names()  %>% as.data.frame() %>% arrange(desc(.)))
  
  
  
  
```
### Boruta

```{r}
source("../functions/select_features_boruta.R")
  initial_variables$Activity<-as.factor(initial_variables$Activity)
boruta_var<-select_maxn_features(initial_variables %>% select(-Anim),
                                 max_num_of_feat = 20,
                                 num_of_samp = 30)
boruta_var

train_dataset_boruta %>% select(initial_variables %>% select(-Anim) %>% names())

boruta_var_notebook<-select_maxn_features(train_dataset_boruta %>% select(initial_variables %>% select(-Anim) %>% names()) ,
                                 max_num_of_feat = 20,
                                 num_of_samp = 30)
```


```{r}
selected_variables <- readr::read_csv("../../../data/topnfeatures/seba-caprino_selected_features.tsv")
a<-selected_variables %>% arrange(variable) %>% unname() %>% unlist()
b<-var_importance_boruta_final %>% arrange(variable) %>% unname() %>% unlist()

a
b
```

## loocv samples
```{r}
setwd("/home/harpo/Dropbox/ongoing-work/git-repos/goat-behavior/")
source("code/R/functions/train_model_loocv.R")
loocv_dataset <- readr::read_delim("data/split/seba-caprino_loocv.tsv",delim="\t")

loocv_sam <- create_loocv_samples(loocv_dataset)
loocv_sam$loocv_test[[1]]
loocv_sam$n_anim

#loocv_sample_test
#loocv_sam$loocv_test
```
## Train loocv

```{r}

setwd("/home/harpo/Dropbox/ongoing-work/git-repos/goat-behavior/")
source("code/R/functions/train_model_loocv.R")
loocv_dataset <- readr::read_delim("data/split/seba-caprino_loocv.tsv",delim="\t")

library(yaml)
  ## Set default parameters
  params <- yaml::read_yaml("params.yaml")
  if(!  "train_model" %in% names(params)) { 
    message("[] Error: No information for training model")
    quit()
  }
  
  grid<-expand.grid(
    depth = params$train_model$depth,
    learning_rate = params$train_model$learning_rate,
    iterations = params$train_model$iterations,
    l2_leaf_reg = params$train_model$l2_leaf_reg,
    rsm = params$train_model$rsm,
    border_count = params$train_model$border_count
  )
  grid <- expand.grid(
    depth = c(4),
    learning_rate = c(0.05),
    iterations = c(1000),
    l2_leaf_reg = c(3.0),
    rsm = c(1),
    border_count = c(64)
  )

selected_variables <- var_importance_boruta_final
results <- 
    train_model_loocv(dataset = loocv_dataset,
                        selected_variables=selected_variables,gridsearch = grid,vfrac = 0.1)

loocv_results %>% loocv_peformance_metrics

```

## Model
```{r}

model<-readRDS("../../../models/boost/seba-caprino_model.rds")
model$pred %>% group_by(Resample,obs) %>% summarise(Sens=sum(pred==obs)/n()) %>% group_by(obs) %>% summarise(Sens_Mean=mean(Sens),Sens_sd=sd(Sens)) %>% filter(obs == "G")  %>% select(Sens_Mean,Sens_sd) %>% as.yaml() %>% write("../../../test.yaml")
```

